
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 21 14:15:18 CEST 2013
//----------------------------------------------------

package eggloop.flow.simhya.simhya.modelchecking.mtl.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 7;
  public static final int POW = 9;
  public static final int UMINUS = 10;
  public static final int NOTEQUAL = 25;
  public static final int GREATER = 29;
  public static final int LROUND = 11;
  public static final int LESS = 28;
  public static final int MINUS = 5;
  public static final int RROUND = 12;
  public static final int NOT = 34;
  public static final int SEMICOLON = 2;
  public static final int AND = 32;
  public static final int WUNTIL = 23;
  public static final int LESSEQUAL = 26;
  public static final int OR = 33;
  public static final int QMARK = 31;
  public static final int COMMA = 3;
  public static final int UNTIL = 22;
  public static final int NEXT = 21;
  public static final int PLUS = 4;
  public static final int EOF = 0;
  public static final int EQUAL = 24;
  public static final int TRUE = 37;
  public static final int error = 1;
  public static final int NUMBER = 36;
  public static final int MOD = 8;
  public static final int GLOBALLY = 19;
  public static final int IMPLY = 35;
  public static final int EQ = 30;
  public static final int GREATEREQUAL = 27;
  public static final int TIMES = 6;
  public static final int LBRACE = 15;
  public static final int LSQUARE = 13;
  public static final int RSQUARE = 14;
  public static final int EVENTUALLY = 18;
  public static final int RBRACE = 16;
  public static final int PROB = 20;
  public static final int FALSE = 38;
  public static final int IDENTIFIER = 17;
}

