/* Generated By:JavaCC: Do not edit this line. HypeParserTokenManager.java */
package com.eggloop.flow.simhya.hype.parser;

/**
 * Token Manager.
 */
public class HypeParserTokenManager implements HypeParserConstants {

    /**
     * Debug output.
     */
    public java.io.PrintStream debugStream = System.out;

    /**
     * Set debug output.
     */
    public void setDebugStream(java.io.PrintStream ds) {
        debugStream = ds;
    }

    private final int jjStopStringLiteralDfa_3(int pos, long active0) {
        switch (pos) {
            default:
                return -1;
        }
    }

    private final int jjStartNfa_3(int pos, long active0) {
        return jjMoveNfa_3(jjStopStringLiteralDfa_3(pos, active0), pos + 1);
    }

    private int jjStopAtPos(int pos, int kind) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        return pos + 1;
    }

    private int jjMoveStringLiteralDfa0_3() {
        switch (curChar) {
            case 38:
                return jjStartNfaWithStates_3(0, 51, 5);
            case 59:
                return jjStopAtPos(0, 30);
            case 64:
                return jjStopAtPos(0, 36);
            case 93:
                return jjStopAtPos(0, 35);
            default:
                return jjMoveNfa_3(9, 0);
        }
    }

    private int jjStartNfaWithStates_3(int pos, int kind, int state) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return pos + 1;
        }
        return jjMoveNfa_3(state, pos + 1);
    }

    private int jjMoveNfa_3(int startState, int curPos) {
        int startsAt = 0;
        jjnewStateCnt = 9;
        int i = 1;
        jjstateSet[0] = startState;
        int kind = 0x7fffffff;
        for (; ; ) {
            if (++jjround == 0x7fffffff)
                ReInitRounds();
            if (curChar < 64) {
                long l = 1L << curChar;
                do {
                    switch (jjstateSet[--i]) {
                        case 9:
                            if ((0x73ffff3b00000200L & l) != 0L) {
                                if (kind > 54)
                                    kind = 54;
                                jjCheckNAddStates(0, 2);
                            } else if (curChar == 38)
                                jjstateSet[jjnewStateCnt++] = 5;
                            else if (curChar == 58)
                                jjstateSet[jjnewStateCnt++] = 2;
                            if ((0x100000200L & l) != 0L)
                                jjCheckNAddTwoStates(0, 3);
                            break;
                        case 0:
                            if ((0x100000200L & l) != 0L)
                                jjCheckNAddTwoStates(0, 3);
                            break;
                        case 1:
                            if (curChar == 62 && kind > 50)
                                kind = 50;
                            break;
                        case 2:
                            if (curChar == 45)
                                jjstateSet[jjnewStateCnt++] = 1;
                            break;
                        case 3:
                            if (curChar == 58)
                                jjstateSet[jjnewStateCnt++] = 2;
                            break;
                        case 4:
                            if ((0x73ffff3b00000200L & l) == 0L)
                                break;
                            if (kind > 54)
                                kind = 54;
                            jjCheckNAddStates(0, 2);
                            break;
                        case 5:
                            if (curChar != 38)
                                break;
                            if (kind > 54)
                                kind = 54;
                            jjCheckNAddStates(0, 2);
                            break;
                        case 6:
                            if (curChar == 38)
                                jjstateSet[jjnewStateCnt++] = 5;
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                long l = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 9:
                            if ((0x7fffffec7fffffeL & l) != 0L) {
                                if (kind > 54)
                                    kind = 54;
                                jjCheckNAddStates(0, 2);
                            } else if (curChar == 124)
                                jjstateSet[jjnewStateCnt++] = 7;
                            break;
                        case 4:
                            if ((0x7fffffec7fffffeL & l) == 0L)
                                break;
                            kind = 54;
                            jjCheckNAddStates(0, 2);
                            break;
                        case 7:
                            if (curChar != 124)
                                break;
                            if (kind > 54)
                                kind = 54;
                            jjCheckNAddStates(0, 2);
                            break;
                        case 8:
                            if (curChar == 124)
                                jjstateSet[jjnewStateCnt++] = 7;
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else {
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        default:
                            break;
                    }
                } while (i != startsAt);
            }
            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            ++curPos;
            if ((i = jjnewStateCnt) == (startsAt = 9 - (jjnewStateCnt = startsAt)))
                return curPos;
            try {
                curChar = input_stream.readChar();
            } catch (java.io.IOException e) {
                return curPos;
            }
        }
    }

    private final int jjStopStringLiteralDfa_2(int pos, long active0) {
        switch (pos) {
            default:
                return -1;
        }
    }

    private final int jjStartNfa_2(int pos, long active0) {
        return jjMoveNfa_2(jjStopStringLiteralDfa_2(pos, active0), pos + 1);
    }

    private int jjMoveStringLiteralDfa0_2() {
        switch (curChar) {
            default:
                return jjMoveNfa_2(0, 0);
        }
    }

    static final long[] jjbitVec0 = {
            0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL
    };

    private int jjMoveNfa_2(int startState, int curPos) {
        int startsAt = 0;
        jjnewStateCnt = 14;
        int i = 1;
        jjstateSet[0] = startState;
        int kind = 0x7fffffff;
        for (; ; ) {
            if (++jjround == 0x7fffffff)
                ReInitRounds();
            if (curChar < 64) {
                long l = 1L << curChar;
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if (curChar == 47)
                                jjAddStates(3, 4);
                            break;
                        case 1:
                            if ((0x3ff001800000000L & l) == 0L)
                                break;
                            if (kind > 49)
                                kind = 49;
                            jjstateSet[jjnewStateCnt++] = 1;
                            break;
                        case 3:
                            if (curChar == 47)
                                jjCheckNAddStates(5, 7);
                            break;
                        case 4:
                            if ((0xffffffffffffdbffL & l) != 0L)
                                jjCheckNAddStates(5, 7);
                            break;
                        case 5:
                            if ((0x2400L & l) != 0L && kind > 5)
                                kind = 5;
                            break;
                        case 6:
                            if (curChar == 10 && kind > 5)
                                kind = 5;
                            break;
                        case 7:
                            if (curChar == 13)
                                jjstateSet[jjnewStateCnt++] = 6;
                            break;
                        case 8:
                            if (curChar == 42)
                                jjCheckNAddTwoStates(9, 10);
                            break;
                        case 9:
                            if ((0xfffffbffffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(9, 10);
                            break;
                        case 10:
                            if (curChar == 42)
                                jjAddStates(8, 9);
                            break;
                        case 11:
                            if ((0xffff7fffffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(12, 10);
                            break;
                        case 12:
                            if ((0xfffffbffffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(12, 10);
                            break;
                        case 13:
                            if (curChar == 47 && kind > 6)
                                kind = 6;
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                long l = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0x7fffffe07fffffeL & l) == 0L)
                                break;
                            if (kind > 49)
                                kind = 49;
                            jjCheckNAdd(1);
                            break;
                        case 1:
                            if ((0x7fffffe87fffffeL & l) == 0L)
                                break;
                            if (kind > 49)
                                kind = 49;
                            jjCheckNAdd(1);
                            break;
                        case 4:
                            jjAddStates(5, 7);
                            break;
                        case 9:
                            jjCheckNAddTwoStates(9, 10);
                            break;
                        case 11:
                        case 12:
                            jjCheckNAddTwoStates(12, 10);
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else {
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 4:
                            if ((jjbitVec0[i2] & l2) != 0L)
                                jjAddStates(5, 7);
                            break;
                        case 9:
                            if ((jjbitVec0[i2] & l2) != 0L)
                                jjCheckNAddTwoStates(9, 10);
                            break;
                        case 11:
                        case 12:
                            if ((jjbitVec0[i2] & l2) != 0L)
                                jjCheckNAddTwoStates(12, 10);
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            }
            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            ++curPos;
            if ((i = jjnewStateCnt) == (startsAt = 14 - (jjnewStateCnt = startsAt)))
                return curPos;
            try {
                curChar = input_stream.readChar();
            } catch (java.io.IOException e) {
                return curPos;
            }
        }
    }

    private final int jjStopStringLiteralDfa_0(int pos, long active0) {
        switch (pos) {
            case 0:
                if ((active0 & 0x80000000000L) != 0L)
                    return 41;
                if ((active0 & 0x3ff80000L) != 0L) {
                    jjmatchedKind = 49;
                    return 4;
                }
                return -1;
            case 1:
                if ((active0 & 0x3ff80000L) != 0L) {
                    jjmatchedKind = 49;
                    jjmatchedPos = 1;
                    return 4;
                }
                return -1;
            case 2:
                if ((active0 & 0x200000L) != 0L)
                    return 4;
                if ((active0 & 0x3fd80000L) != 0L) {
                    jjmatchedKind = 49;
                    jjmatchedPos = 2;
                    return 4;
                }
                return -1;
            case 3:
                if ((active0 & 0x2a080000L) != 0L)
                    return 4;
                if ((active0 & 0x15d00000L) != 0L) {
                    jjmatchedKind = 49;
                    jjmatchedPos = 3;
                    return 4;
                }
                return -1;
            case 4:
                if ((active0 & 0x14d00000L) != 0L)
                    return 4;
                if ((active0 & 0x1000000L) != 0L) {
                    jjmatchedKind = 49;
                    jjmatchedPos = 4;
                    return 4;
                }
                return -1;
            case 5:
                if ((active0 & 0x1000000L) != 0L) {
                    jjmatchedKind = 49;
                    jjmatchedPos = 5;
                    return 4;
                }
                return -1;
            case 6:
                if ((active0 & 0x1000000L) != 0L) {
                    jjmatchedKind = 49;
                    jjmatchedPos = 6;
                    return 4;
                }
                return -1;
            case 7:
                if ((active0 & 0x1000000L) != 0L)
                    return 4;
                return -1;
            default:
                return -1;
        }
    }

    private final int jjStartNfa_0(int pos, long active0) {
        return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
    }

    private int jjMoveStringLiteralDfa0_0() {
        switch (curChar) {
            case 35:
                return jjMoveStringLiteralDfa1_0(0x7e000L);
            case 38:
                return jjStopAtPos(0, 51);
            case 40:
                return jjStopAtPos(0, 37);
            case 41:
                return jjStopAtPos(0, 38);
            case 42:
                return jjStopAtPos(0, 44);
            case 43:
                return jjStopAtPos(0, 42);
            case 44:
                return jjStopAtPos(0, 39);
            case 46:
                return jjStartNfaWithStates_0(0, 43, 41);
            case 58:
                jjmatchedKind = 31;
                return jjMoveStringLiteralDfa1_0(0x20100000000L);
            case 59:
                return jjStopAtPos(0, 30);
            case 60:
                return jjStopAtPos(0, 45);
            case 61:
                return jjStopAtPos(0, 33);
            case 62:
                return jjStopAtPos(0, 46);
            case 64:
                return jjStopAtPos(0, 36);
            case 91:
                return jjStopAtPos(0, 34);
            case 101:
                return jjMoveStringLiteralDfa1_0(0x12000000L);
            case 102:
                return jjMoveStringLiteralDfa1_0(0x1000000L);
            case 103:
                return jjMoveStringLiteralDfa1_0(0x800000L);
            case 104:
                return jjMoveStringLiteralDfa1_0(0x80000L);
            case 105:
                return jjMoveStringLiteralDfa1_0(0x28000000L);
            case 109:
                return jjMoveStringLiteralDfa1_0(0x100000L);
            case 112:
                return jjMoveStringLiteralDfa1_0(0x400000L);
            case 114:
                return jjMoveStringLiteralDfa1_0(0x4000000L);
            case 118:
                return jjMoveStringLiteralDfa1_0(0x200000L);
            case 124:
                return jjMoveStringLiteralDfa1_0(0x800000000000L);
            default:
                return jjMoveNfa_0(0, 0);
        }
    }

    private int jjMoveStringLiteralDfa1_0(long active0) {
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(0, active0);
            return 1;
        }
        switch (curChar) {
            case 45:
                return jjMoveStringLiteralDfa2_0(active0, 0x20000000000L);
            case 61:
                if ((active0 & 0x100000000L) != 0L)
                    return jjStopAtPos(1, 32);
                break;
            case 97:
                return jjMoveStringLiteralDfa2_0(active0, 0x600000L);
            case 99:
                return jjMoveStringLiteralDfa2_0(active0, 0x30000L);
            case 100:
                return jjMoveStringLiteralDfa2_0(active0, 0x2000L);
            case 101:
                return jjMoveStringLiteralDfa2_0(active0, 0x4000000L);
            case 109:
                return jjMoveStringLiteralDfa2_0(active0, 0x4000L);
            case 110:
                return jjMoveStringLiteralDfa2_0(active0, 0x28000000L);
            case 111:
                return jjMoveStringLiteralDfa2_0(active0, 0x100000L);
            case 115:
                return jjMoveStringLiteralDfa2_0(active0, 0x48000L);
            case 117:
                return jjMoveStringLiteralDfa2_0(active0, 0x1800000L);
            case 118:
                return jjMoveStringLiteralDfa2_0(active0, 0x10000000L);
            case 120:
                return jjMoveStringLiteralDfa2_0(active0, 0x2000000L);
            case 121:
                return jjMoveStringLiteralDfa2_0(active0, 0x80000L);
            case 124:
                if ((active0 & 0x800000000000L) != 0L)
                    return jjStopAtPos(1, 47);
                break;
            default:
                break;
        }
        return jjStartNfa_0(0, active0);
    }

    private int jjMoveStringLiteralDfa2_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(0, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(1, active0);
            return 2;
        }
        switch (curChar) {
            case 62:
                if ((active0 & 0x20000000000L) != 0L)
                    return jjStopAtPos(2, 41);
                break;
            case 97:
                return jjMoveStringLiteralDfa3_0(active0, 0x804000L);
            case 100:
                return jjMoveStringLiteralDfa3_0(active0, 0x100000L);
            case 101:
                return jjMoveStringLiteralDfa3_0(active0, 0x10002000L);
            case 102:
                return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
            case 105:
                return jjMoveStringLiteralDfa3_0(active0, 0x20000000L);
            case 110:
                return jjMoveStringLiteralDfa3_0(active0, 0x1000000L);
            case 111:
                return jjMoveStringLiteralDfa3_0(active0, 0x30000L);
            case 112:
                return jjMoveStringLiteralDfa3_0(active0, 0x2080000L);
            case 114:
                if ((active0 & 0x200000L) != 0L)
                    return jjStartNfaWithStates_0(2, 21, 4);
                return jjMoveStringLiteralDfa3_0(active0, 0x400000L);
            case 115:
                return jjMoveStringLiteralDfa3_0(active0, 0x4000000L);
            case 117:
                return jjMoveStringLiteralDfa3_0(active0, 0x8000L);
            case 121:
                return jjMoveStringLiteralDfa3_0(active0, 0x40000L);
            default:
                break;
        }
        return jjStartNfa_0(1, active0);
    }

    private int jjMoveStringLiteralDfa3_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(1, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(2, active0);
            return 3;
        }
        switch (curChar) {
            case 97:
                return jjMoveStringLiteralDfa4_0(active0, 0x400000L);
            case 98:
                return jjMoveStringLiteralDfa4_0(active0, 0x8000L);
            case 99:
                return jjMoveStringLiteralDfa4_0(active0, 0x1000000L);
            case 101:
                if ((active0 & 0x80000L) != 0L)
                    return jjStartNfaWithStates_0(3, 19, 4);
                return jjMoveStringLiteralDfa4_0(active0, 0x4100000L);
            case 102:
                return jjMoveStringLiteralDfa4_0(active0, 0x2000L);
            case 108:
                if ((active0 & 0x8000000L) != 0L)
                    return jjStartNfaWithStates_0(3, 27, 4);
                break;
            case 109:
                return jjMoveStringLiteralDfa4_0(active0, 0x10000L);
            case 110:
                return jjMoveStringLiteralDfa4_0(active0, 0x10020000L);
            case 112:
                return jjMoveStringLiteralDfa4_0(active0, 0x4000L);
            case 114:
                if ((active0 & 0x2000000L) != 0L)
                    return jjStartNfaWithStates_0(3, 25, 4);
                return jjMoveStringLiteralDfa4_0(active0, 0x800000L);
            case 115:
                return jjMoveStringLiteralDfa4_0(active0, 0x40000L);
            case 116:
                if ((active0 & 0x20000000L) != 0L)
                    return jjStartNfaWithStates_0(3, 29, 4);
                break;
            default:
                break;
        }
        return jjStartNfa_0(2, active0);
    }

    private int jjMoveStringLiteralDfa4_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(2, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(3, active0);
            return 4;
        }
        switch (curChar) {
            case 99:
                return jjMoveStringLiteralDfa5_0(active0, 0x8000L);
            case 100:
                if ((active0 & 0x800000L) != 0L)
                    return jjStartNfaWithStates_0(4, 23, 4);
                break;
            case 105:
                return jjMoveStringLiteralDfa5_0(active0, 0x2000L);
            case 108:
                if ((active0 & 0x100000L) != 0L)
                    return jjStartNfaWithStates_0(4, 20, 4);
                break;
            case 109:
                if ((active0 & 0x400000L) != 0L)
                    return jjStartNfaWithStates_0(4, 22, 4);
                break;
            case 112:
                return jjMoveStringLiteralDfa5_0(active0, 0x14000L);
            case 116:
                if ((active0 & 0x4000000L) != 0L)
                    return jjStartNfaWithStates_0(4, 26, 4);
                else if ((active0 & 0x10000000L) != 0L)
                    return jjStartNfaWithStates_0(4, 28, 4);
                return jjMoveStringLiteralDfa5_0(active0, 0x1060000L);
            default:
                break;
        }
        return jjStartNfa_0(3, active0);
    }

    private int jjMoveStringLiteralDfa5_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(3, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(4, active0);
            return 5;
        }
        switch (curChar) {
            case 101:
                return jjMoveStringLiteralDfa6_0(active0, 0x40000L);
            case 105:
                return jjMoveStringLiteralDfa6_0(active0, 0x1004000L);
            case 110:
                return jjMoveStringLiteralDfa6_0(active0, 0x2000L);
            case 111:
                return jjMoveStringLiteralDfa6_0(active0, 0x18000L);
            case 114:
                return jjMoveStringLiteralDfa6_0(active0, 0x20000L);
            default:
                break;
        }
        return jjStartNfa_0(4, active0);
    }

    private int jjMoveStringLiteralDfa6_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(4, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(5, active0);
            return 6;
        }
        switch (curChar) {
            case 105:
                return jjMoveStringLiteralDfa7_0(active0, 0x2000L);
            case 109:
                if ((active0 & 0x40000L) != 0L)
                    return jjStopAtPos(6, 18);
                return jjMoveStringLiteralDfa7_0(active0, 0x8000L);
            case 110:
                return jjMoveStringLiteralDfa7_0(active0, 0x14000L);
            case 111:
                return jjMoveStringLiteralDfa7_0(active0, 0x1020000L);
            default:
                break;
        }
        return jjStartNfa_0(5, active0);
    }

    private int jjMoveStringLiteralDfa7_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(5, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(6, active0);
            return 7;
        }
        switch (curChar) {
            case 101:
                return jjMoveStringLiteralDfa8_0(active0, 0x10000L);
            case 103:
                return jjMoveStringLiteralDfa8_0(active0, 0x4000L);
            case 108:
                return jjMoveStringLiteralDfa8_0(active0, 0x20000L);
            case 110:
                if ((active0 & 0x1000000L) != 0L)
                    return jjStartNfaWithStates_0(7, 24, 4);
                break;
            case 112:
                return jjMoveStringLiteralDfa8_0(active0, 0x8000L);
            case 116:
                return jjMoveStringLiteralDfa8_0(active0, 0x2000L);
            default:
                break;
        }
        return jjStartNfa_0(6, active0);
    }

    private int jjMoveStringLiteralDfa8_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(6, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(7, active0);
            return 8;
        }
        switch (curChar) {
            case 105:
                return jjMoveStringLiteralDfa9_0(active0, 0x2000L);
            case 108:
                return jjMoveStringLiteralDfa9_0(active0, 0x20000L);
            case 110:
                return jjMoveStringLiteralDfa9_0(active0, 0x10000L);
            case 111:
                return jjMoveStringLiteralDfa9_0(active0, 0x8000L);
            case 115:
                if ((active0 & 0x4000L) != 0L)
                    return jjStopAtPos(8, 14);
                break;
            default:
                break;
        }
        return jjStartNfa_0(7, active0);
    }

    private int jjMoveStringLiteralDfa9_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(7, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(8, active0);
            return 9;
        }
        switch (curChar) {
            case 101:
                return jjMoveStringLiteralDfa10_0(active0, 0x20000L);
            case 110:
                return jjMoveStringLiteralDfa10_0(active0, 0x8000L);
            case 111:
                return jjMoveStringLiteralDfa10_0(active0, 0x2000L);
            case 116:
                return jjMoveStringLiteralDfa10_0(active0, 0x10000L);
            default:
                break;
        }
        return jjStartNfa_0(8, active0);
    }

    private int jjMoveStringLiteralDfa10_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(8, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(9, active0);
            return 10;
        }
        switch (curChar) {
            case 101:
                return jjMoveStringLiteralDfa11_0(active0, 0x8000L);
            case 110:
                return jjMoveStringLiteralDfa11_0(active0, 0x2000L);
            case 114:
                if ((active0 & 0x20000L) != 0L)
                    return jjStopAtPos(10, 17);
                break;
            case 115:
                if ((active0 & 0x10000L) != 0L)
                    return jjStopAtPos(10, 16);
                break;
            default:
                break;
        }
        return jjStartNfa_0(9, active0);
    }

    private int jjMoveStringLiteralDfa11_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(9, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(10, active0);
            return 11;
        }
        switch (curChar) {
            case 110:
                return jjMoveStringLiteralDfa12_0(active0, 0x8000L);
            case 115:
                if ((active0 & 0x2000L) != 0L)
                    return jjStopAtPos(11, 13);
                break;
            default:
                break;
        }
        return jjStartNfa_0(10, active0);
    }

    private int jjMoveStringLiteralDfa12_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(10, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(11, active0);
            return 12;
        }
        switch (curChar) {
            case 116:
                return jjMoveStringLiteralDfa13_0(active0, 0x8000L);
            default:
                break;
        }
        return jjStartNfa_0(11, active0);
    }

    private int jjMoveStringLiteralDfa13_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_0(11, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(12, active0);
            return 13;
        }
        switch (curChar) {
            case 115:
                if ((active0 & 0x8000L) != 0L)
                    return jjStopAtPos(13, 15);
                break;
            default:
                break;
        }
        return jjStartNfa_0(12, active0);
    }

    private int jjStartNfaWithStates_0(int pos, int kind, int state) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return pos + 1;
        }
        return jjMoveNfa_0(state, pos + 1);
    }

    private int jjMoveNfa_0(int startState, int curPos) {
        int startsAt = 0;
        jjnewStateCnt = 41;
        int i = 1;
        jjstateSet[0] = startState;
        int kind = 0x7fffffff;
        for (; ; ) {
            if (++jjround == 0x7fffffff)
                ReInitRounds();
            if (curChar < 64) {
                long l = 1L << curChar;
                do {
                    switch (jjstateSet[--i]) {
                        case 41:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(17, 18);
                            if ((0x3ff000000000000L & l) != 0L) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAdd(8);
                            }
                            break;
                        case 0:
                            if ((0x3ff000000000000L & l) != 0L) {
                                if (kind > 48)
                                    kind = 48;
                                jjCheckNAddStates(10, 16);
                            } else if (curChar == 47)
                                jjAddStates(17, 18);
                            else if (curChar == 46)
                                jjCheckNAddTwoStates(8, 17);
                            else if (curChar == 45)
                                jjCheckNAddStates(19, 24);
                            else if (curChar == 39)
                                jjCheckNAddTwoStates(1, 2);
                            break;
                        case 1:
                            if ((0x100000200L & l) != 0L)
                                jjCheckNAddTwoStates(1, 2);
                            break;
                        case 2:
                            if (curChar == 61 && kind > 40)
                                kind = 40;
                            break;
                        case 4:
                            if ((0x3ff001800000000L & l) == 0L)
                                break;
                            if (kind > 49)
                                kind = 49;
                            jjstateSet[jjnewStateCnt++] = 4;
                            break;
                        case 5:
                            if (curChar == 45)
                                jjCheckNAddStates(19, 24);
                            break;
                        case 6:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 48)
                                kind = 48;
                            jjCheckNAdd(6);
                            break;
                        case 7:
                            if (curChar == 46)
                                jjCheckNAdd(8);
                            break;
                        case 8:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 48)
                                kind = 48;
                            jjCheckNAdd(8);
                            break;
                        case 9:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(9, 10);
                            break;
                        case 10:
                            if (curChar != 46)
                                break;
                            if (kind > 48)
                                kind = 48;
                            jjCheckNAdd(11);
                            break;
                        case 11:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 48)
                                kind = 48;
                            jjCheckNAdd(11);
                            break;
                        case 12:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(12, 13);
                            break;
                        case 14:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(15);
                            break;
                        case 15:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 48)
                                kind = 48;
                            jjCheckNAdd(15);
                            break;
                        case 16:
                            if (curChar == 46)
                                jjCheckNAdd(17);
                            break;
                        case 17:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(17, 18);
                            break;
                        case 19:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(20);
                            break;
                        case 20:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 48)
                                kind = 48;
                            jjCheckNAdd(20);
                            break;
                        case 21:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(21, 22);
                            break;
                        case 22:
                            if (curChar == 46)
                                jjCheckNAddTwoStates(23, 24);
                            break;
                        case 23:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(23, 24);
                            break;
                        case 25:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(26);
                            break;
                        case 26:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 48)
                                kind = 48;
                            jjCheckNAdd(26);
                            break;
                        case 27:
                            if ((0x3ff000000000000L & l) == 0L)
                                break;
                            if (kind > 48)
                                kind = 48;
                            jjCheckNAddStates(10, 16);
                            break;
                        case 28:
                            if (curChar == 46)
                                jjCheckNAddTwoStates(8, 17);
                            break;
                        case 29:
                            if (curChar == 47)
                                jjAddStates(17, 18);
                            break;
                        case 30:
                            if (curChar == 47)
                                jjCheckNAddStates(25, 27);
                            break;
                        case 31:
                            if ((0xffffffffffffdbffL & l) != 0L)
                                jjCheckNAddStates(25, 27);
                            break;
                        case 32:
                            if ((0x2400L & l) != 0L && kind > 5)
                                kind = 5;
                            break;
                        case 33:
                            if (curChar == 10 && kind > 5)
                                kind = 5;
                            break;
                        case 34:
                            if (curChar == 13)
                                jjstateSet[jjnewStateCnt++] = 33;
                            break;
                        case 35:
                            if (curChar == 42)
                                jjCheckNAddTwoStates(36, 37);
                            break;
                        case 36:
                            if ((0xfffffbffffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(36, 37);
                            break;
                        case 37:
                            if (curChar == 42)
                                jjAddStates(28, 29);
                            break;
                        case 38:
                            if ((0xffff7fffffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(39, 37);
                            break;
                        case 39:
                            if ((0xfffffbffffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(39, 37);
                            break;
                        case 40:
                            if (curChar == 47 && kind > 6)
                                kind = 6;
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                long l = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0x7fffffe07fffffeL & l) == 0L)
                                break;
                            if (kind > 49)
                                kind = 49;
                            jjCheckNAdd(4);
                            break;
                        case 4:
                            if ((0x7fffffe87fffffeL & l) == 0L)
                                break;
                            if (kind > 49)
                                kind = 49;
                            jjCheckNAdd(4);
                            break;
                        case 13:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(30, 31);
                            break;
                        case 18:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(32, 33);
                            break;
                        case 24:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(34, 35);
                            break;
                        case 31:
                            jjAddStates(25, 27);
                            break;
                        case 36:
                            jjCheckNAddTwoStates(36, 37);
                            break;
                        case 38:
                        case 39:
                            jjCheckNAddTwoStates(39, 37);
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else {
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 31:
                            if ((jjbitVec0[i2] & l2) != 0L)
                                jjAddStates(25, 27);
                            break;
                        case 36:
                            if ((jjbitVec0[i2] & l2) != 0L)
                                jjCheckNAddTwoStates(36, 37);
                            break;
                        case 38:
                        case 39:
                            if ((jjbitVec0[i2] & l2) != 0L)
                                jjCheckNAddTwoStates(39, 37);
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            }
            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            ++curPos;
            if ((i = jjnewStateCnt) == (startsAt = 41 - (jjnewStateCnt = startsAt)))
                return curPos;
            try {
                curChar = input_stream.readChar();
            } catch (java.io.IOException e) {
                return curPos;
            }
        }
    }

    private final int jjStopStringLiteralDfa_4(int pos, long active0) {
        switch (pos) {
            default:
                return -1;
        }
    }

    private final int jjStartNfa_4(int pos, long active0) {
        return jjMoveNfa_4(jjStopStringLiteralDfa_4(pos, active0), pos + 1);
    }

    private int jjMoveStringLiteralDfa0_4() {
        switch (curChar) {
            case 44:
                return jjStopAtPos(0, 39);
            case 45:
                return jjStopAtPos(0, 52);
            default:
                return jjMoveNfa_4(0, 0);
        }
    }

    private int jjMoveNfa_4(int startState, int curPos) {
        int startsAt = 0;
        jjnewStateCnt = 1;
        int i = 1;
        jjstateSet[0] = startState;
        int kind = 0x7fffffff;
        for (; ; ) {
            if (++jjround == 0x7fffffff)
                ReInitRounds();
            if (curChar < 64) {
                long l = 1L << curChar;
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0x3ff400100000200L & l) == 0L)
                                break;
                            kind = 53;
                            jjstateSet[jjnewStateCnt++] = 0;
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                long l = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0x7fffffe87fffffeL & l) == 0L)
                                break;
                            kind = 53;
                            jjstateSet[jjnewStateCnt++] = 0;
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else {
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        default:
                            break;
                    }
                } while (i != startsAt);
            }
            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            ++curPos;
            if ((i = jjnewStateCnt) == (startsAt = 1 - (jjnewStateCnt = startsAt)))
                return curPos;
            try {
                curChar = input_stream.readChar();
            } catch (java.io.IOException e) {
                return curPos;
            }
        }
    }

    private final int jjStopStringLiteralDfa_1(int pos, long active0) {
        switch (pos) {
            case 0:
                if ((active0 & 0x3ff80000L) != 0L) {
                    jjmatchedKind = 49;
                    return 1;
                }
                return -1;
            case 1:
                if ((active0 & 0x3ff80000L) != 0L) {
                    jjmatchedKind = 49;
                    jjmatchedPos = 1;
                    return 1;
                }
                return -1;
            case 2:
                if ((active0 & 0x200000L) != 0L)
                    return 1;
                if ((active0 & 0x3fd80000L) != 0L) {
                    jjmatchedKind = 49;
                    jjmatchedPos = 2;
                    return 1;
                }
                return -1;
            case 3:
                if ((active0 & 0x2a080000L) != 0L)
                    return 1;
                if ((active0 & 0x15d00000L) != 0L) {
                    jjmatchedKind = 49;
                    jjmatchedPos = 3;
                    return 1;
                }
                return -1;
            case 4:
                if ((active0 & 0x14d00000L) != 0L)
                    return 1;
                if ((active0 & 0x1000000L) != 0L) {
                    jjmatchedKind = 49;
                    jjmatchedPos = 4;
                    return 1;
                }
                return -1;
            case 5:
                if ((active0 & 0x1000000L) != 0L) {
                    jjmatchedKind = 49;
                    jjmatchedPos = 5;
                    return 1;
                }
                return -1;
            case 6:
                if ((active0 & 0x1000000L) != 0L) {
                    jjmatchedKind = 49;
                    jjmatchedPos = 6;
                    return 1;
                }
                return -1;
            default:
                return -1;
        }
    }

    private final int jjStartNfa_1(int pos, long active0) {
        return jjMoveNfa_1(jjStopStringLiteralDfa_1(pos, active0), pos + 1);
    }

    private int jjMoveStringLiteralDfa0_1() {
        switch (curChar) {
            case 40:
                return jjStopAtPos(0, 37);
            case 41:
                return jjStopAtPos(0, 38);
            case 44:
                return jjStopAtPos(0, 39);
            case 61:
                return jjStopAtPos(0, 33);
            case 101:
                return jjMoveStringLiteralDfa1_1(0x12000000L);
            case 102:
                return jjMoveStringLiteralDfa1_1(0x1000000L);
            case 103:
                return jjMoveStringLiteralDfa1_1(0x800000L);
            case 104:
                return jjMoveStringLiteralDfa1_1(0x80000L);
            case 105:
                return jjMoveStringLiteralDfa1_1(0x28000000L);
            case 109:
                return jjMoveStringLiteralDfa1_1(0x100000L);
            case 112:
                return jjMoveStringLiteralDfa1_1(0x400000L);
            case 114:
                return jjMoveStringLiteralDfa1_1(0x4000000L);
            case 118:
                return jjMoveStringLiteralDfa1_1(0x200000L);
            default:
                return jjMoveNfa_1(0, 0);
        }
    }

    private int jjMoveStringLiteralDfa1_1(long active0) {
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_1(0, active0);
            return 1;
        }
        switch (curChar) {
            case 97:
                return jjMoveStringLiteralDfa2_1(active0, 0x600000L);
            case 101:
                return jjMoveStringLiteralDfa2_1(active0, 0x4000000L);
            case 110:
                return jjMoveStringLiteralDfa2_1(active0, 0x28000000L);
            case 111:
                return jjMoveStringLiteralDfa2_1(active0, 0x100000L);
            case 117:
                return jjMoveStringLiteralDfa2_1(active0, 0x1800000L);
            case 118:
                return jjMoveStringLiteralDfa2_1(active0, 0x10000000L);
            case 120:
                return jjMoveStringLiteralDfa2_1(active0, 0x2000000L);
            case 121:
                return jjMoveStringLiteralDfa2_1(active0, 0x80000L);
            default:
                break;
        }
        return jjStartNfa_1(0, active0);
    }

    private int jjMoveStringLiteralDfa2_1(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_1(0, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_1(1, active0);
            return 2;
        }
        switch (curChar) {
            case 97:
                return jjMoveStringLiteralDfa3_1(active0, 0x800000L);
            case 100:
                return jjMoveStringLiteralDfa3_1(active0, 0x100000L);
            case 101:
                return jjMoveStringLiteralDfa3_1(active0, 0x10000000L);
            case 102:
                return jjMoveStringLiteralDfa3_1(active0, 0x8000000L);
            case 105:
                return jjMoveStringLiteralDfa3_1(active0, 0x20000000L);
            case 110:
                return jjMoveStringLiteralDfa3_1(active0, 0x1000000L);
            case 112:
                return jjMoveStringLiteralDfa3_1(active0, 0x2080000L);
            case 114:
                if ((active0 & 0x200000L) != 0L)
                    return jjStartNfaWithStates_1(2, 21, 1);
                return jjMoveStringLiteralDfa3_1(active0, 0x400000L);
            case 115:
                return jjMoveStringLiteralDfa3_1(active0, 0x4000000L);
            default:
                break;
        }
        return jjStartNfa_1(1, active0);
    }

    private int jjMoveStringLiteralDfa3_1(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_1(1, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_1(2, active0);
            return 3;
        }
        switch (curChar) {
            case 97:
                return jjMoveStringLiteralDfa4_1(active0, 0x400000L);
            case 99:
                return jjMoveStringLiteralDfa4_1(active0, 0x1000000L);
            case 101:
                if ((active0 & 0x80000L) != 0L)
                    return jjStartNfaWithStates_1(3, 19, 1);
                return jjMoveStringLiteralDfa4_1(active0, 0x4100000L);
            case 108:
                if ((active0 & 0x8000000L) != 0L)
                    return jjStartNfaWithStates_1(3, 27, 1);
                break;
            case 110:
                return jjMoveStringLiteralDfa4_1(active0, 0x10000000L);
            case 114:
                if ((active0 & 0x2000000L) != 0L)
                    return jjStartNfaWithStates_1(3, 25, 1);
                return jjMoveStringLiteralDfa4_1(active0, 0x800000L);
            case 116:
                if ((active0 & 0x20000000L) != 0L)
                    return jjStartNfaWithStates_1(3, 29, 1);
                break;
            default:
                break;
        }
        return jjStartNfa_1(2, active0);
    }

    private int jjMoveStringLiteralDfa4_1(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_1(2, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_1(3, active0);
            return 4;
        }
        switch (curChar) {
            case 100:
                if ((active0 & 0x800000L) != 0L)
                    return jjStartNfaWithStates_1(4, 23, 1);
                break;
            case 108:
                if ((active0 & 0x100000L) != 0L)
                    return jjStartNfaWithStates_1(4, 20, 1);
                break;
            case 109:
                if ((active0 & 0x400000L) != 0L)
                    return jjStartNfaWithStates_1(4, 22, 1);
                break;
            case 116:
                if ((active0 & 0x4000000L) != 0L)
                    return jjStartNfaWithStates_1(4, 26, 1);
                else if ((active0 & 0x10000000L) != 0L)
                    return jjStartNfaWithStates_1(4, 28, 1);
                return jjMoveStringLiteralDfa5_1(active0, 0x1000000L);
            default:
                break;
        }
        return jjStartNfa_1(3, active0);
    }

    private int jjMoveStringLiteralDfa5_1(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_1(3, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_1(4, active0);
            return 5;
        }
        switch (curChar) {
            case 105:
                return jjMoveStringLiteralDfa6_1(active0, 0x1000000L);
            default:
                break;
        }
        return jjStartNfa_1(4, active0);
    }

    private int jjMoveStringLiteralDfa6_1(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_1(4, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_1(5, active0);
            return 6;
        }
        switch (curChar) {
            case 111:
                return jjMoveStringLiteralDfa7_1(active0, 0x1000000L);
            default:
                break;
        }
        return jjStartNfa_1(5, active0);
    }

    private int jjMoveStringLiteralDfa7_1(long old0, long active0) {
        if (((active0 &= old0)) == 0L)
            return jjStartNfa_1(5, old0);
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_1(6, active0);
            return 7;
        }
        switch (curChar) {
            case 110:
                if ((active0 & 0x1000000L) != 0L)
                    return jjStartNfaWithStates_1(7, 24, 1);
                break;
            default:
                break;
        }
        return jjStartNfa_1(6, active0);
    }

    private int jjStartNfaWithStates_1(int pos, int kind, int state) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return pos + 1;
        }
        return jjMoveNfa_1(state, pos + 1);
    }

    private int jjMoveNfa_1(int startState, int curPos) {
        int startsAt = 0;
        jjnewStateCnt = 14;
        int i = 1;
        jjstateSet[0] = startState;
        int kind = 0x7fffffff;
        for (; ; ) {
            if (++jjround == 0x7fffffff)
                ReInitRounds();
            if (curChar < 64) {
                long l = 1L << curChar;
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if (curChar == 47)
                                jjAddStates(3, 4);
                            break;
                        case 1:
                            if ((0x3ff001800000000L & l) == 0L)
                                break;
                            if (kind > 49)
                                kind = 49;
                            jjstateSet[jjnewStateCnt++] = 1;
                            break;
                        case 3:
                            if (curChar == 47)
                                jjCheckNAddStates(5, 7);
                            break;
                        case 4:
                            if ((0xffffffffffffdbffL & l) != 0L)
                                jjCheckNAddStates(5, 7);
                            break;
                        case 5:
                            if ((0x2400L & l) != 0L && kind > 5)
                                kind = 5;
                            break;
                        case 6:
                            if (curChar == 10 && kind > 5)
                                kind = 5;
                            break;
                        case 7:
                            if (curChar == 13)
                                jjstateSet[jjnewStateCnt++] = 6;
                            break;
                        case 8:
                            if (curChar == 42)
                                jjCheckNAddTwoStates(9, 10);
                            break;
                        case 9:
                            if ((0xfffffbffffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(9, 10);
                            break;
                        case 10:
                            if (curChar == 42)
                                jjAddStates(8, 9);
                            break;
                        case 11:
                            if ((0xffff7fffffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(12, 10);
                            break;
                        case 12:
                            if ((0xfffffbffffffffffL & l) != 0L)
                                jjCheckNAddTwoStates(12, 10);
                            break;
                        case 13:
                            if (curChar == 47 && kind > 6)
                                kind = 6;
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                long l = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0x7fffffe07fffffeL & l) == 0L)
                                break;
                            if (kind > 49)
                                kind = 49;
                            jjCheckNAdd(1);
                            break;
                        case 1:
                            if ((0x7fffffe87fffffeL & l) == 0L)
                                break;
                            if (kind > 49)
                                kind = 49;
                            jjCheckNAdd(1);
                            break;
                        case 4:
                            jjAddStates(5, 7);
                            break;
                        case 9:
                            jjCheckNAddTwoStates(9, 10);
                            break;
                        case 11:
                        case 12:
                            jjCheckNAddTwoStates(12, 10);
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            } else {
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 4:
                            if ((jjbitVec0[i2] & l2) != 0L)
                                jjAddStates(5, 7);
                            break;
                        case 9:
                            if ((jjbitVec0[i2] & l2) != 0L)
                                jjCheckNAddTwoStates(9, 10);
                            break;
                        case 11:
                        case 12:
                            if ((jjbitVec0[i2] & l2) != 0L)
                                jjCheckNAddTwoStates(12, 10);
                            break;
                        default:
                            break;
                    }
                } while (i != startsAt);
            }
            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            ++curPos;
            if ((i = jjnewStateCnt) == (startsAt = 14 - (jjnewStateCnt = startsAt)))
                return curPos;
            try {
                curChar = input_stream.readChar();
            } catch (java.io.IOException e) {
                return curPos;
            }
        }
    }

    static final int[] jjnextStates = {
            4, 6, 8, 3, 8, 4, 5, 7, 11, 13, 6, 9, 10, 12, 13, 21,
            22, 30, 35, 6, 7, 9, 12, 16, 21, 31, 32, 34, 38, 40, 14, 15,
            19, 20, 25, 26,
    };

    /**
     * Token literal values.
     */
    public static final String[] jjstrLiteralImages = {
            "", null, null, null, null, null, null, null, null, null, null, null, null,
            "\43\144\145\146\151\156\151\164\151\157\156\163", "\43\155\141\160\160\151\156\147\163",
            "\43\163\165\142\143\157\155\160\157\156\145\156\164\163", "\43\143\157\155\160\157\156\145\156\164\163",
            "\43\143\157\156\164\162\157\154\154\145\162", "\43\163\171\163\164\145\155", "\150\171\160\145", "\155\157\144\145\154",
            "\166\141\162", "\160\141\162\141\155", "\147\165\141\162\144",
            "\146\165\156\143\164\151\157\156", "\145\170\160\162", "\162\145\163\145\164", "\151\156\146\154",
            "\145\166\145\156\164", "\151\156\151\164", "\73", "\72", "\72\75", "\75", "\133", "\135", "\100",
            "\50", "\51", "\54", null, "\72\55\76", "\53", "\56", "\52", "\74", "\76",
            "\174\174", null, null, null, "\46", "\55", null, null, null, null, null, null,};

    /**
     * Lexer state names.
     */
    public static final String[] lexStateNames = {
            "DEFAULT",
            "RESET",
            "ID",
            "MATH",
            "MATH_RED",
    };

    /**
     * Lex State array.
     */
    public static final int[] jjnewLexState = {
            -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 2, -1, -1, -1, -1,
            -1, 1, -1, -1, -1, 0, -1, -1, -1, 4, 0, 3, -1, -1, -1, 3, -1, -1, -1, -1, -1, -1, -1, -1, -1,
            0, 0, -1, -1, -1, -1, -1, -1, -1,
    };
    static final long[] jjtoToken = {
            0x7fffffffffe001L,
    };
    static final long[] jjtoSkip = {
            0x7eL,
    };
    protected SimpleCharStream input_stream;
    private final int[] jjrounds = new int[41];
    private final int[] jjstateSet = new int[82];
    private final StringBuilder jjimage = new StringBuilder();
    private StringBuilder image = jjimage;
    private int jjimageLen;
    private int lengthOfMatch;
    protected char curChar;

    /**
     * Constructor.
     */
    public HypeParserTokenManager(SimpleCharStream stream) {
        if (SimpleCharStream.staticFlag)
            throw new Error("ERROR: Cannot use a static CharStream class with a non-static lexical analyzer.");
        input_stream = stream;
    }

    /**
     * Constructor.
     */
    public HypeParserTokenManager(SimpleCharStream stream, int lexState) {
        this(stream);
        SwitchTo(lexState);
    }

    /**
     * Reinitialise parser.
     */
    public void ReInit(SimpleCharStream stream) {
        jjmatchedPos = jjnewStateCnt = 0;
        curLexState = defaultLexState;
        input_stream = stream;
        ReInitRounds();
    }

    private void ReInitRounds() {
        int i;
        jjround = 0x80000001;
        for (i = 41; i-- > 0; )
            jjrounds[i] = 0x80000000;
    }

    /**
     * Reinitialise parser.
     */
    public void ReInit(SimpleCharStream stream, int lexState) {
        ReInit(stream);
        SwitchTo(lexState);
    }

    /**
     * Switch to specified lex state.
     */
    public void SwitchTo(int lexState) {
        if (lexState >= 5 || lexState < 0)
            throw new TokenMgrError("Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.", TokenMgrError.INVALID_LEXICAL_STATE);
        else
            curLexState = lexState;
    }

    protected Token jjFillToken() {
        final Token t;
        final String curTokenImage;
        final int beginLine;
        final int endLine;
        final int beginColumn;
        final int endColumn;
        String im = jjstrLiteralImages[jjmatchedKind];
        curTokenImage = (im == null) ? input_stream.GetImage() : im;
        beginLine = input_stream.getBeginLine();
        beginColumn = input_stream.getBeginColumn();
        endLine = input_stream.getEndLine();
        endColumn = input_stream.getEndColumn();
        t = Token.newToken(jjmatchedKind, curTokenImage);

        t.beginLine = beginLine;
        t.endLine = endLine;
        t.beginColumn = beginColumn;
        t.endColumn = endColumn;

        return t;
    }

    int curLexState = 0;
    int defaultLexState = 0;
    int jjnewStateCnt;
    int jjround;
    int jjmatchedPos;
    int jjmatchedKind;

    /**
     * Get the next Token.
     */
    public Token getNextToken() {
        Token matchedToken;
        int curPos = 0;

        EOFLoop:
        for (; ; ) {
            try {
                curChar = input_stream.BeginToken();
            } catch (java.io.IOException e) {
                jjmatchedKind = 0;
                matchedToken = jjFillToken();
                return matchedToken;
            }
            image = jjimage;
            image.setLength(0);
            jjimageLen = 0;

            switch (curLexState) {
                case 0:
                    try {
                        input_stream.backup(0);
                        while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
                            curChar = input_stream.BeginToken();
                    } catch (java.io.IOException e1) {
                        continue EOFLoop;
                    }
                    jjmatchedKind = 0x7fffffff;
                    jjmatchedPos = 0;
                    curPos = jjMoveStringLiteralDfa0_0();
                    break;
                case 1:
                    try {
                        input_stream.backup(0);
                        while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
                            curChar = input_stream.BeginToken();
                    } catch (java.io.IOException e1) {
                        continue EOFLoop;
                    }
                    jjmatchedKind = 0x7fffffff;
                    jjmatchedPos = 0;
                    curPos = jjMoveStringLiteralDfa0_1();
                    break;
                case 2:
                    try {
                        input_stream.backup(0);
                        while (curChar <= 32 && (0x100002600L & (1L << curChar)) != 0L)
                            curChar = input_stream.BeginToken();
                    } catch (java.io.IOException e1) {
                        continue EOFLoop;
                    }
                    jjmatchedKind = 0x7fffffff;
                    jjmatchedPos = 0;
                    curPos = jjMoveStringLiteralDfa0_2();
                    break;
                case 3:
                    jjmatchedKind = 0x7fffffff;
                    jjmatchedPos = 0;
                    curPos = jjMoveStringLiteralDfa0_3();
                    break;
                case 4:
                    jjmatchedKind = 0x7fffffff;
                    jjmatchedPos = 0;
                    curPos = jjMoveStringLiteralDfa0_4();
                    break;
            }
            if (jjmatchedKind != 0x7fffffff) {
                if (jjmatchedPos + 1 < curPos)
                    input_stream.backup(curPos - jjmatchedPos - 1);
                if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
                    matchedToken = jjFillToken();
                    TokenLexicalActions(matchedToken);
                    if (jjnewLexState[jjmatchedKind] != -1)
                        curLexState = jjnewLexState[jjmatchedKind];
                    return matchedToken;
                } else {
                    if (jjnewLexState[jjmatchedKind] != -1)
                        curLexState = jjnewLexState[jjmatchedKind];
                    continue EOFLoop;
                }
            }
            int error_line = input_stream.getEndLine();
            int error_column = input_stream.getEndColumn();
            String error_after = null;
            boolean EOFSeen = false;
            try {
                input_stream.readChar();
                input_stream.backup(1);
            } catch (java.io.IOException e1) {
                EOFSeen = true;
                error_after = curPos <= 1 ? "" : input_stream.GetImage();
                if (curChar == '\n' || curChar == '\r') {
                    error_line++;
                    error_column = 0;
                } else
                    error_column++;
            }
            if (!EOFSeen) {
                input_stream.backup(1);
                error_after = curPos <= 1 ? "" : input_stream.GetImage();
            }
            throw new TokenMgrError(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenMgrError.LEXICAL_ERROR);
        }
    }

    void TokenLexicalActions(Token matchedToken) {
        switch (jjmatchedKind) {
            case 33:
                image.append(jjstrLiteralImages[33]);
                lengthOfMatch = jjstrLiteralImages[33].length();
                if (curLexState == DEFAULT) SwitchTo(MATH);
                else if (curLexState == RESET) SwitchTo(DEFAULT);
                break;
            case 39:
                image.append(jjstrLiteralImages[39]);
                lengthOfMatch = jjstrLiteralImages[39].length();
                if (curLexState == MATH_RED) SwitchTo(MATH);
                break;
            case 49:
                image.append(input_stream.GetSuffix(jjimageLen + (lengthOfMatch = jjmatchedPos + 1)));
                if (curLexState == ID) SwitchTo(DEFAULT);
                break;
            default:
                break;
        }
    }

    private void jjCheckNAdd(int state) {
        if (jjrounds[state] != jjround) {
            jjstateSet[jjnewStateCnt++] = state;
            jjrounds[state] = jjround;
        }
    }

    private void jjAddStates(int start, int end) {
        do {
            jjstateSet[jjnewStateCnt++] = jjnextStates[start];
        } while (start++ != end);
    }

    private void jjCheckNAddTwoStates(int state1, int state2) {
        jjCheckNAdd(state1);
        jjCheckNAdd(state2);
    }

    private void jjCheckNAddStates(int start, int end) {
        do {
            jjCheckNAdd(jjnextStates[start]);
        } while (start++ != end);
    }

}
