
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 16 15:24:50 BST 2012
//----------------------------------------------------

package eggloop.flow.simhya.simhya.modelchecking.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 9;
  public static final int MOD = 11;
  public static final int FORMULA = 27;
  public static final int SEMICOLON = 2;
  public static final int PLUS = 7;
  public static final int DEFINE = 6;
  public static final int EQUAL = 17;
  public static final int NOTEQUAL = 18;
  public static final int IDENTIFIER = 16;
  public static final int POW = 12;
  public static final int GREATER = 22;
  public static final int LESSEQUAL = 19;
  public static final int COLON = 4;
  public static final int RROUND = 15;
  public static final int RESERVED = 24;
  public static final int COMMA = 3;
  public static final int MTL = 26;
  public static final int NUMBER = 23;
  public static final int EOF = 0;
  public static final int DIVIDE = 10;
  public static final int LROUND = 14;
  public static final int MINUS = 8;
  public static final int error = 1;
  public static final int ASSIGN = 5;
  public static final int PARAM = 25;
  public static final int GREATEREQUAL = 20;
  public static final int LESS = 21;
  public static final int UMINUS = 13;
}

